# Generated by Django 5.2.7 on 2025-10-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="UdiFiaWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_number", models.CharField(max_length=50)),
                ("udr_fia_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("gtin_change", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_type", models.CharField(max_length=50)),
                ("product_category_unit", models.CharField(max_length=50)),
                ("product_category_level", models.CharField(max_length=50)),
                ("gtin_evaluation", models.BooleanField(null=True)),
                ("has_udi_health_impact", models.CharField(max_length=5)),
                ("has_impact_in_new_gtin", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="ChangesInvolved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_description", models.TextField(blank=True, null=True)),
                (
                    "change_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.changecategories",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.udifiaworkflow",
                    ),
                ),
            ],
        ),
    ]
