# Generated by Django 5.2.7 on 2025-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changesinvolved",
            name="change_category",
            field=models.CharField(default="asdfds", max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ChangeCategories",
        ),
    ]
