# Generated by Django 5.2.7 on 2025-10-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0002_alter_changesinvolved_change_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="has_impact_in_new_gtin",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="has_udi_health_impact",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="product_category_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="product_category_unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="product_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="udifiaworkflow",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
