# Generated by Django 5.2.7 on 2025-10-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_udifiaworkflow_has_impact_in_new_gtin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udifiaworkflow',
            name='gtin_change',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
