# Generated by Django 5.2.7 on 2025-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_udifiaworkflow_gtin_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='udifiaworkflow',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
