# Generated by Django 5.2.7 on 2025-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_udifiaworkflow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(max_length=50)),
                ('udr_fia_number', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('gtin_change', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product_category_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('product_category_level', models.CharField(blank=True, max_length=50, null=True)),
                ('gtin_evaluation', models.CharField(blank=True, max_length=20, null=True)),
                ('has_udi_health_impact', models.CharField(blank=True, max_length=5, null=True)),
                ('has_impact_in_new_gtin', models.CharField(blank=True, max_length=5, null=True)),
                ('action_item', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='udifiaworkflow',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
