# Generated by Django 5.2.7 on 2025-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_rule_udifiaworkflow_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
