# Generated by Django 5.2.7 on 2025-11-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_rule_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='change_number',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='udr_fia_number',
        ),
    ]
