# Generated by Django 5.2.7 on 2025-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_remove_rule_change_number_remove_rule_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLMWindchillMockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(max_length=30)),
                ('udi_fia_number', models.CharField(max_length=30)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='udifiaworkflow',
            name='change_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='udifiaworkflow',
            name='udr_fia_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
