# Generated by Django 5.2.7 on 2025-11-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_plmwindchillmockdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='product_category_level',
            new_name='field_type',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='product_category_unit',
            new_name='gude_field_number',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='action_item',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='country',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='gtin_change',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='gtin_evaluation',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='has_impact_in_new_gtin',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='has_udi_health_impact',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='region',
        ),
        migrations.AddField(
            model_name='rule',
            name='add_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='additional_change_request_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='budi_attribute_eudamed_only',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='change_condition_or_scenarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='data_attribute_ha_field_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='data_property',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='data_source_outcome_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='delete_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='dri_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='edit_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='gs1_gtin_trigger_100782299_appendix_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='gtin_outcome_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='gude_field_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='health_authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='health_authority_gtin_trigger',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='jjmt_use_directive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='jnj_udi_data_element',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='mandatory_field_in_database',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='udi_regulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
